### ISSUE TITLE
MADDPG Config

### ISSUE THREAD

**Issue by florin-pop** [facebookresearch/BenchMARL#86]
Thank you for the amazing work you've put into VMAS and BenchMARL.

I tried and failed to reproduce the results from https://github.com/proroklab/VectorizedMultiAgentSimulator/issues/62 and I am not sure if I am missing some important piece of configuration.

When I run:
`python benchmarl/run.py task=pettingzoo/simple_reference algorithm=mappo`
the logs appear to indicate that the training works: the reward increases until it reaches a plateau and the videos show the agents moving.

However, when I try to use MADDPG by running:
`python benchmarl/run.py task=pettingzoo/simple_reference algorithm=maddpg`
the training process proceeds, but the agents are not exploring the environment or communicating.
This is not singular to this task, as it happens for simple_spread as well.
If I try to use MADDPG with VMAS/nagivation it works as expected.
I experimented with different versions of PettingZoo and benchMARL, but it didn't seem to make a difference so I'm thinking that I may be missing something.

My config is the default:
```
algorithm_config:
  desc: null
  value:
    delay_value: true
    loss_function: l2
    share_param_critic: true
    use_tanh_mapping: true
algorithm_name:
  desc: null
  value: maddpg
continuous_actions:
  desc: null
  value: true
environment_name:
  desc: null
  value: pettingzoo
experiment_config:
  desc: null
  value:
    adam_eps: 1.0e-06
    checkpoint_interval: 300000.0
    clip_grad_norm: true
    clip_grad_val: 5.0
    create_json: true
    evaluation: true
    evaluation_deterministic_actions: true
    evaluation_episodes: 200
    evaluation_interval: 60000
    exploration_anneal_frames: 1000000
    exploration_eps_end: 0.01
    exploration_eps_init: 0.8
    gamma: 0.9
    hard_target_update_frequency: 5
    loggers:
    - wandb
    lr: 5.0e-05
    max_n_frames: 10000000
    max_n_iters: null
    off_policy_collected_frames_per_batch: 6000
    off_policy_init_random_frames: 0
    off_policy_memory_size: 1000000
    off_policy_n_envs_per_worker: 60
    off_policy_n_optimizer_steps: 1000
    off_policy_train_batch_size: 128
    on_policy_collected_frames_per_batch: 60000
    on_policy_minibatch_size: 4096
    on_policy_n_envs_per_worker: 600
    on_policy_n_minibatch_iters: 45
    polyak_tau: 0.005
    prefer_continuous_actions: true
    render: true
    restore_file: null
    sampling_device: cuda
    save_folder: artifacts
    share_policy_params: false
    soft_target_update: true
    train_device: cuda
model_config:
  desc: null
  value:
    activation_class: torch.nn.modules.activation.Tanh
    activation_kwargs: null
    layer_class: torch.nn.modules.linear.Linear
    norm_class: null
    norm_kwargs: null
    num_cells:
    - 256
    - 256
model_name:
  desc: null
  value: mlp
on_policy:
  desc: null
  value: false
seed:
  desc: null
  value: 0
task_config:
  desc: null
  value:
    continuous_actions: true
    local_ratio: 0.5
    max_cycles: 100
    task: simple_reference_v3
task_name:
  desc: null
  value: simple_reference
```
